//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ForRent
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Description is required")]
        [StringLength(1000, MinimumLength = 6, ErrorMessage = "Description must to me from 6 to 1000 symbols lenght")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Phone is required")]
        [RegularExpression(@"\d{3,10}", ErrorMessage = "Phone should contains up to 10 numbers only")]
        public string phone { get; set; }
        [DisplayName("Select image #1")]
        public byte[] image { get; set; }
        [DisplayName("Select image #2")]
        public byte[] image1 { get; set; }
    }
}
