//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageStore
    {
        public int ID { get; set; }
        public byte[] FileContent { get; set; }
        public string MimeType { get; set; }
        public string FileName { get; set; }
    
        public virtual AdTable AdTable { get; set; }
    }
}
